{{- define "bfebench.protocolParameters" -}}
{{- $parametersList := list -}}
{{ range $key, $value := . }}
{{- $parametersList = append $parametersList (printf "-p %s %s" $key ($value | toString)) -}}
{{- end -}}
{{- $parametersList | join " " -}}
{{- end -}}
