
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PYTHON_DEFAULT_VERSION: "3.9"


unittests:
  image: python:${python_version}
  before_script:
    - pip install --upgrade pip
    - pip install . coverage
    - mkdir -p testdata && ./tools/generate-test-data.py --lower-boundary-power 15 --upper-boundary-power 15 testdata
  script:
    - coverage run -m unittest discover tests
    - coverage xml
    - coverage report --precision=2
  parallel:
    matrix:
      - python_version: ["3.7", "3.8", "3.9"]
  artifacts:
    reports:
      cobertura: coverage.xml


flake8:
  image: python:${python_version}
  before_script:
    - pip install --upgrade pip
    - pip install flake8
  script:
    - python -m flake8
  parallel:
    matrix:
      - python_version: ["3.7", "3.8", "3.9"]


mypy:
  image: python:${python_version}
  before_script:
    - pip install --upgrade pip
    - pip install . mypy
    - python -m mypy --install-types --non-interactive
  script:
    - python -m mypy
  parallel:
    matrix:
      - python_version: ["3.7", "3.8", "3.9"]


isort:
  image: python:${PYTHON_DEFAULT_VERSION}
  before_script:
    - pip install isort
  script:
    - isort --check .


black:
  image: python:${PYTHON_DEFAULT_VERSION}
  before_script:
    - pip install black
  script:
    - black --check .
