repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args:
          - "--strict"
        additional_dependencies:
          # core dependencies
          - "eth-tester==0.6.0b4"
          - "hexbytes==0.2.2"
          - "Jinja2==3.0.1"
          - "pycryptodome==3.10.1"
          - "py-evm==0.5.0a1"
          - "py-solc-x==1.1.0"
          - "PyYAML==5.4.1"
          - "tabulate==0.8.9"
          - "web3==5.26.0"
          # typing dependencies
          - "typing_extensions"  # see https://mypy.readthedocs.io/en/stable/literal_types.html#literal-types
          - "types-PyYAML"
          - "types-setuptools"
          - "types-tabulate"
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
