protocols:
  - name: Fairswap
    parameters:
      timeout: 10
  - name: FairswapReusable
    parameters:
      timeout: 10
  - name: StateChannelFileSale
    parameters:
      file_sale_iterations: 10
      timeout: 10
sizes:
  - 1KiB
  - 2KiB
  - 4KiB
  - 8KiB
  - 16KiB
  - 32KiB
  - 64KiB
  - 128KiB
  - 256KiB
  - 512KiB
  - 1MiB
