protocols:
  - name: StateChannelFileSale
    parameters:
      file_sale_iterations: 3
      timeout: 20
    strategy_pairs:
      - seller: Faithful
        buyer: Faithful
      - seller: Grieving
        buyer: Faithful
      - seller: KeyForging
        buyer: Faithful
      - seller: RootForging
        buyer: Faithful
      - seller: NodeForging
        buyer: Faithful
      - seller: LeafForging
        buyer: Faithful

  - name: Fairswap
    parameters:
      timeout: 20
    strategy_pairs:
      - seller: Faithful
        buyer: Faithful
      - seller: Faithful
        buyer: Grieving
      - seller: RootForging
        buyer: Faithful
      - seller: NodeForging
        buyer: Faithful
      - seller: LeafForging
        buyer: Faithful

sizes:
  - 1MiB
  - 512KiB
  - 256KiB
  - 128KiB
  - 64KiB
  - 32KiB
  - 16KiB
  - 8KiB
  - 4KiB
  - 2KiB
  - 1KiB
