@startuml
[*] --> Idle

Idle --> Requested : [B] _request
Idle --> RequestTimeout : [B] TIMEOUT
Idle --> Finalized : [B] _finalize
Requested --> Initialized : [S] _initialize
Requested --> InitTimeout : [S] TIMEOUT
Initialized --> Accepted : [B] _accept
Initialized --> AcceptTimeout : [B] TIMEOUT
Accepted --> KeyRevealed : [S] _revealKey
note on link
  seller reveals key and
  changes balances
end note
Accepted --> KeyRevealTimeout : [S] TIMEOUT
KeyRevealed --> Idle : [B] _confirm
KeyRevealed --> ConfirmTimeout : [B] TIMEOUT

RequestTimeout --> DisputeRegistered : [S] register()
InitTimeout --> DisputeRegistered : [B] register()
AcceptTimeout --> DisputeRegistered : [S] register()
KeyRevealTimeout --> DisputeRegistered : [B] register()
ConfirmTimeout --> DisputeRegistered : [S] register()

DisputeRegistered --> DisputeRegistered : [S/B] register()
note on link
  seller and buyer can
  register latest state
end note
DisputeRegistered --> DisputeExecution : [S/B] TIMEOUT
DisputeExecution --> DisputeExecution : [S/B] process()
note on link
  seller and buyer can process
  single transition step
end note
DisputeExecution --> DisputeTimedOut : [S/B] TIMEOUT
DisputeTimedOut --> ReadyForWithdraw : [S/B] conclude()

Finalized --> ReadyForWithdraw : [S] _conclude()
@enduml
