uploadURL: ""
uploadSecret: ""

iterations: 100

readinessLogTimeout: 300

job:
  resources:
    requests:
      cpu: "1000m"


bulkConfig:
  protocols:
    - name: Fairswap
      parameters:
      strategyPairs:
        - seller: Faithful
          buyer: Faithful
        - seller: Faithful
          buyer: Grieving
        - seller: RootForging
          buyer: Faithful
        - seller: NodeForging
          buyer: Faithful
        - seller: LeafForging
          buyer: Faithful

    - name: StateChannelFileSale
      parameters:
        file_sale_iterations: 3
      strategyPairs:
        - seller: Faithful
          buyer: Faithful
        - seller: Grieving
          buyer: Faithful
        - seller: KeyForging
          buyer: Faithful
        - seller: RootForging
          buyer: Faithful
        - seller: NodeForging
          buyer: Faithful
        - seller: LeafForging
          buyer: Faithful

  fileSizes:
  - size: 1MiB
    timeout: 60
  - size: 512KiB
    timeout: 30
  - size: 256KiB
    timeout: 20
  - size: 128KiB
    timeout: 15
  - size: 64KiB
    timeout: 12
  - size: 32KiB
    timeout: 11
  - size: 16KiB
    timeout: 10
  - size: 8KiB
    timeout: 10
  - size: 4KiB
    timeout: 10
  - size: 2KiB
    timeout: 10
  - size: 1KiB
    timeout: 10
