uploadURL: ""
uploadSecret: ""

iterations: 100

readinessLogTimeout: 300

bulkConfig:
  protocols:
    - name: Fairswap
      parameters:
        timeout: 20
      strategyPairs:
        - seller: Faithful
          buyer: Faithful
        - seller: Faithful
          buyer: Grieving
        - seller: RootForging
          buyer: Faithful
        - seller: NodeForging
          buyer: Faithful
        - seller: LeafForging
          buyer: Faithful

    - name: StateChannelFileSale
      parameters:
        file_sale_iterations: 3
        timeout: 20
      strategyPairs:
        - seller: Faithful
          buyer: Faithful
        - seller: Grieving
          buyer: Faithful
        - seller: KeyForging
          buyer: Faithful
        - seller: RootForging
          buyer: Faithful
        - seller: NodeForging
          buyer: Faithful
        - seller: LeafForging
          buyer: Faithful

  fileSizes:
  - 1MiB
  - 512KiB
  - 256KiB
  - 128KiB
  - 64KiB
  - 32KiB
  - 16KiB
  - 8KiB
  - 4KiB
  - 2KiB
  - 1KiB
